const lang = {
  en: {
    SEARCH: "Search",
    GPT_SEARCH_PLACE_HOLDER: "What whould you like to watch today?",
    NOW_PLAYING: "Now Playing",
    TOP_RATED_MOVIES: "Top Rated Movies",
    POPULAR: "Popular",
    UPCOMING_MOVIES: "Upcoming Movies",
    PLAY: "Play",
    MORE_INFO: "More Info",
    HOME_PAGE: "Home Page",
    GPT_SEARCH: "GPT Search",
    SIGN_OUT: "Sign Out",
  },
  hi: {
    SEARCH: "खोज",
    GPT_SEARCH_PLACE_HOLDER: "आज आप क्या देखना पसंद करेंगे?",
    NOW_PLAYING: "अभी चल रही फ़िल्में",
    TOP_RATED_MOVIES: "शीर्ष रेटेड फिल्में",
    POPULAR: "लोकप्रिय फ़िल्में",
    UPCOMING_MOVIES: "आने वाली फिल्में",
    PLAY: "फिल्म चलाएं",
    MORE_INFO: "और जानकारी",
    HOME_PAGE: "होम पेज",
    GPT_SEARCH: "जीपीटी खोज",
    SIGN_OUT: "साइन आउट",
  },
  es: {
    SEARCH: "Buscar",
    GPT_SEARCH_PLACE_HOLDER: "¿Qué te gustaría ver hoy?",
    NOW_PLAYING: "Ahora reproduciendo películas",
    TOP_RATED_MOVIES: "Películas mejor valoradas",
    POPULAR: "Películas populares",
    UPCOMING_MOVIES: "Próximas películas",
    PLAY: "Reproducir película",
    MORE_INFO: "Más información",
    HOME_PAGE: "Página de inicio",
    GPT_SEARCH: "Búsqueda GPT",
    SIGN_OUT: "Desconectar",
  },
  fr: {
    SEARCH: "Recherche",
    GPT_SEARCH_PLACE_HOLDER: "Qu’aimeriez-vous regarder aujourd’hui ?",
    NOW_PLAYING: "Lecture de films en cours",
    TOP_RATED_MOVIES: "Films les mieux notés",
    POPULAR: "Films populaires",
    UPCOMING_MOVIES: "Films à venir",
    PLAY: "Lancer le film",
    MORE_INFO: "Plus d'informations",
    HOME_PAGE: "Page d'accueil",
    GPT_SEARCH: "Recherche GPT",
    SIGN_OUT: "Se déconnecter",
  },
};

export default lang;
